// source of all information: https://www.forbes.com/advisor/investing/best-crypto-exchanges/
// article creators: Taylor Tepper,  John Schmidt

export const exchangeList = [
    {
        name: "Coinbase",
        rating: 4.5,
        cryptoAmount: "50+",
        fee: "varies",
        logo: "/assets/logos/coinbase-logo.png",
        url: "https://www.coinbase.com/",
        benefits: ["Beginner-friendly interface.", "Easy purchase process.", "Strong user reviews and security ratings.", "Educational elements rewards users with cryptocurrency when they learn about crypto."],
        drawbacks: ["High fees for convenience.", "Must use a separate more complex platform to access lower pricing structure."],
    },
    {
        name: "Kraken",
        rating: 4.8,
        cryptoAmount: "50+",
        fee: "0.16%/0.26%",
        logo: "/assets/logos/kraken-logo.png",
        url: "https://www.kraken.com/en-us/",
        benefits: ["Sophisticated trading features (e.g. margin), that might appeal to advanced users.", "High cybersecurity ratings."],
        drawbacks: ["May be too complex for true beginner users."],
    },
    {
        name: "Binance.US",
        rating: 4.9,
        cryptoAmount: "50+",
        fee: "0.1%/0.1%",
        logo: "/assets/logos/binance-logo.png",
        url: "https://www.binance.us/en/home",
        benefits: ["Volume and exchange-token discount, which can make already-low fees almost negligible.", "50+ cryptocurrencies currently available for trading.", "Basic order types as well as OTC trading enabled."],
        drawbacks: ["Coin offerings are limited compared to Binance and even other major exchanges.", "No support for margin trading."],
    },
    {
        name: "Crypto.com",
        rating: 4.7,
        cryptoAmount: "100+",
        fee: "0.40%/0.40%",
        logo: "/assets/logos/crypto-com-logo.png",
        url: "https://crypto.com/",
        benefits: ["Those with high balances in Crypto.com’s proprietary stablecoin (CRO) can reap discounts on trading fees and enhanced benefits.", "Limited margin trading currently available.", "High cybersecurity ratings."],
        drawbacks: ["Higher trading fees for low-volume crypto investors."],
    },
    {
        name: "Gemini",
        rating: 4.5,
        cryptoAmount: "40+",
        fee: "varies",
        logo: "/assets/logos/gemini-logo.jpg",
        url: "https://www.gemini.com/",
        benefits: ["Simple, easy-to-use interface.", "Available in all 50 states, including New York, a common omission from other crypto exchanges’ offerings."],
        drawbacks: ["Convoluted fee (and high) structure when not spot trading."],
    },
    {
        name: "Gate.io",
        rating: 4.5,
        cryptoAmount: "650+",
        fee: "0.2%/0.2%",
        logo: "/assets/logos/gateio-logo.png",
        url: "https://www.gate.io/",
        benefits: ["Huge array of tradable coins with low trading fees.", "Can lower trading fees further with large Gate stablecoin holdings."],
        drawbacks: ["Trading is based on a U.S. dollar stablecoin, not fiat currency.", "complex interface"],
    },
    {
        name: "KuCoin",
        rating: 4.1,
        cryptoAmount: "300+",
        fee: "0.1%/0.1%",
        logo: "/assets/logos/kucoin-logo.png",
        url: "https://www.kucoin.com/",
        benefits: ["Hundreds of tradable cryptos with low fees.", "Can decrease trading fees by 20% by paying with KuCoin’s proprietary KCS stablecoin.", "Automated and margin-based trading available."],
        drawbacks: ["Trading relies on U.S. dollar stablecoins, not fiat currency.", "Though you can use U.S. dollars to buy select crypto, you must do so using an OTC, peer-to-peer market that may be too complex for beginner investors."],
    },
    {
        name: "Bitstamp",
        rating: 3.4,
        cryptoAmount: "20+",
        fee: "0.5%/0.5%",
        logo: "/assets/logos/bitstamp-logo.png",
        url: "https://www.bitstamp.net/",
        benefits: ["Advanced charting features.", "98% of customer assets are held offline"],
        drawbacks: ["Past hacking costing $5 million", "Higher trading fees than other leaders until you trade more than $10,000 a month in crypto."],
    },
    {
        name: "Bittrex",
        rating: 3.4,
        cryptoAmount: "350+",
        fee: "0.75%/0.75%",
        logo: "/assets/logos/bittrexglobal-logo.png",
        url: "https://bittrex.com/",
        benefits: ["Instant buy/sell platform with easy interface for beginner traders.", "Hundreds of coins available for advanced traders."],
        drawbacks: ["High fees for low-volume traders.", "Lower cybersecurity score than other leaders in space."],
    },
    {
        name: "bitFlyer",
        rating: 3.3,
        cryptoAmount: "Less than 10",
        fee: "0.1%/0.1%",
        logo: "/assets/logos/bitflyer-logo.png",
        url: "https://bitflyer.com/en-us/",
        benefits: ["Industry-low fees."],
        drawbacks: ["May be too complex for beginners and lacks detailed educational resources.", "Very few cryptocurrencies are available to trade.", "Low cyber-security ranking"],
    },
]